"""Generate token-budgeted markdown summaries for agent consumption."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from specify_cli.memory.decisions import DecisionStore
    from specify_cli.memory.failures import FailureStore

MAX_DECISION_ENTRIES = 30
MAX_FAILURE_SIGNATURES = 20
MAX_FIELD_WIDTH = 60


def _truncate(text: str, max_len: int = MAX_FIELD_WIDTH) -> str:
    """Truncate text to max_len, appending '...' if shortened."""
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def generate_decisions_summary(
    store: "DecisionStore", output_path: Path
) -> Path:
    """Generate a markdown summary of recent architectural decisions.

    Produces a table of the most recent decisions (up to 30), sorted
    oldest-first for reading order. Uses the newest entry's timestamp
    as the "Last updated" value for idempotent output.

    Args:
        store: DecisionStore to read from.
        output_path: Where to write the summary markdown.

    Returns:
        The output_path for convenience.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    all_entries = store.list_all()
    total = len(all_entries)

    if total == 0:
        output_path.write_text(
            "# Recent Architectural Decisions\n\n"
            "> Auto-generated by Polaris. Do not edit manually.\n"
            "> No decisions recorded yet.\n",
            encoding="utf-8",
        )
        return output_path

    # Take the last N entries (most recent), but display oldest-first
    shown_entries = all_entries[-MAX_DECISION_ENTRIES:]
    shown = len(shown_entries)

    # Use newest entry's timestamp for stable "Last updated"
    last_updated = shown_entries[-1].timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# Recent Architectural Decisions",
        "",
        "> Auto-generated by Polaris. Do not edit manually.",
        f"> Last updated: {last_updated} | Entries: {shown} of {total}",
        "",
        "| When | Context | Decision | Rationale |",
        "|------|---------|----------|-----------|",
    ]

    for entry in shown_entries:
        when = entry.timestamp.strftime("%Y-%m-%d")
        ctx = _truncate(entry.context)
        dec = _truncate(entry.decision)
        rat = _truncate(entry.rationale)
        lines.append(f"| {when} | {ctx} | {dec} | {rat} |")

    lines.append("")  # Trailing newline
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def generate_failures_summary(
    store: "FailureStore", output_path: Path
) -> Path:
    """Generate a markdown summary of resolved failure patterns.

    Groups entries by error_signature, shows only signatures with a verified
    resolution, and caps at 20 unique signatures. Uses the newest entry's
    timestamp for stable "Last updated" value.

    Args:
        store: FailureStore to read from.
        output_path: Where to write the summary markdown.

    Returns:
        The output_path for convenience.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    resolved = store.get_resolved()

    if not resolved:
        output_path.write_text(
            "# Known Failure Patterns and Fixes\n\n"
            "> Auto-generated by Polaris. Do not edit manually.\n"
            "> No resolved failure patterns yet.\n",
            encoding="utf-8",
        )
        return output_path

    # Group by signature, pick newest entry per group
    sig_map: dict[str, "list"] = {}
    for entry in resolved:
        sig = entry.error_signature
        if sig not in sig_map:
            sig_map[sig] = entry
        elif entry.timestamp > sig_map[sig].timestamp:
            sig_map[sig] = entry

    total_sigs = len(sig_map)

    # Sort by timestamp (newest first), take top N
    representatives = sorted(
        sig_map.values(), key=lambda e: e.timestamp, reverse=True
    )[:MAX_FAILURE_SIGNATURES]

    # Use newest entry's timestamp for stable output
    last_updated = representatives[0].timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")
    shown = len(representatives)

    lines = [
        "# Known Failure Patterns and Fixes",
        "",
        "> Auto-generated by Polaris. Do not edit manually.",
        f"> Last updated: {last_updated} | Patterns: {shown} of {total_sigs}",
        "",
        "| Signature | Error Pattern | Fix | Platform | Verified |",
        "|-----------|--------------|-----|----------|----------|",
    ]

    for entry in representatives:
        sig_short = entry.error_signature[:8]
        error_pat = _truncate(entry.error_message)
        fix = _truncate(entry.resolution)
        verified = "Yes" if entry.resolution_verified else "No"
        lines.append(
            f"| {sig_short} | {error_pat} | {fix} | {entry.platform} | {verified} |"
        )

    lines.append("")  # Trailing newline
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
